name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Make the production plugin bundle
        run: |
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          npm install
          npm run build
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: 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
        with:
          files: |
            ./path/to/release/file1
            ./path/to/release/file2
          tag_name: v1.2_6.4.2-free # Corrected input: tag_name
          release_name: v1.2_6.4.2-free
