name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Make the production plugin bundle
        run: |
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          npm install
          npm run build
      - name: Perform Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: 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
        with:
          name: v1.2_6.4.2-free
          tag_name: v1.2_6.4.2-free
          generate_release_notes: true
          files: |
            dist/*.tar.gz
